# netlify.toml

[build]
  command = "npm run build" # The command Netlify will run to build your site
  publish = "wordgame/dist"          # The directory containing your built site (output of `npm run build`)
  functions = "wordgame/api"         # The directory where your Netlify Functions are located

[[redirects]]
  from = "wordgame/*"
  to = "wordgame/index.html"
  status = 200
